'use strict';
const {spawn}=require('child_process');
const http=require('http');
const server=spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:'18080'}});
let out=''; server.stdout.on('data',d=>out+=d); server.stderr.on('data',d=>out+=d);
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function open(){return new Promise((resolve,reject)=>{const w=new WebSocket('ws://127.0.0.1:18080');w.addEventListener('open',()=>resolve(w),{once:true});w.addEventListener('error',reject,{once:true})})}
function next(w,pred,timeout=3000){return new Promise((resolve,reject)=>{const t=setTimeout(()=>{w.removeEventListener('message',on);reject(new Error('timeout'))},timeout);function on(ev){let m;try{m=JSON.parse(ev.data)}catch{return}if(pred(m)){clearTimeout(t);w.removeEventListener('message',on);resolve(m)}}w.addEventListener('message',on)})}
(async()=>{try{await wait(300);const a=await open(),b=await open();a.send(JSON.stringify({type:'create_room',name:'Alice',avatar:'cat',target:500}));const ja=await next(a,m=>m.type==='joined');b.send(JSON.stringify({type:'join_room',code:ja.code,name:'Bob',avatar:'dog',target:500}));await next(b,m=>m.type==='joined');await next(a,m=>m.type==='snapshot'&&m.state.players.every(Boolean));a.send(JSON.stringify({type:'start_game'}));const sa=await next(a,m=>m.type==='snapshot'&&m.state.started&&m.state.players[m.state.meIndex].hand?.length===5);const sb=await next(b,m=>m.type==='snapshot'&&m.state.started&&m.state.players[m.state.meIndex].hand?.length===5);if(sa.state.players[1-sa.state.meIndex].hand!==undefined)throw new Error('Fuite de main adverse côté Alice');if(sb.state.players[1-sb.state.meIndex].hand!==undefined)throw new Error('Fuite de main adverse côté Bob');const current=sa.state.currentIndex;const w=current===sa.state.meIndex?a:b;w.send(JSON.stringify({type:'draw'}));const sdraw=await next(w,m=>m.type==='snapshot'&&m.state.phase==='normal_discard');if(sdraw.state.players[sdraw.state.meIndex].hand.length!==6)throw new Error('La pioche ne donne pas 6 cartes');console.log('OK: salon, 2 joueurs, confidentialité des mains, distribution et pioche synchronisées.');a.close();b.close();process.exitCode=0}catch(e){console.error('ECHEC:',e);process.exitCode=1}finally{server.kill()}})();
